apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-depl
  name: test-depl
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-depl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-depl
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
